// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_helix_version.test.ts.

/** The version of the `@ggdna/dna-helix` package. */
export const dnaHelixVersion = '0.2.0';
